version: "3.9" # optional since v1.27.0
services:
  api:
    build:
      context: api
      dockerfile: ../Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - GITHUB_ID=f1487f8457bfdbb2a147
      - GITHUB_SECRET=2052c20bb99679602aa16f526e13f827353adfcf
    depends_on:
      - redis

  client:
    build:
      context: client
      dockerfile: ../Dockerfile
    environment:
      GITHUB_ID: f1487f8457bfdbb2a147
      GITHUB_SECRET: 2052c20bb99679602aa16f526e13f827353adfcf
      SERVER_API_URL: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

  queue_admin:
    build:
      context: queue-admin
      dockerfile: ../Dockerfile
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "3002:3002"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
